### Email usado generado con https://temp-mail.org/en/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODA4OWI4N2UyODdkMmUyZTViZmE1NDEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTQ4OTg3NiwiZXhwIjoxNzQ1NDk3MDc2fQ.lRphiykw0rZDLvk2IV0lBVM6viQADcdqXqHj_amvka0
@email = podim46911@lushosa.com
@clientId = 680a09aa59a82c110730d1c3
@userId = 68089b87e287d2e2e5bfa541

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "claveSegura123"
}

### Obtener datos del usuario autenticado
GET http://localhost:3000/users/user
Authorization: Bearer {{token}}

### createClient
POST http://localhost:3000/clients/create-client
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "John Doe 2",
    "cif": "A23456789",
    "address": {
        "street": "Not Main Street",
        "number": 122,
        "postal": 54321,
        "city": "Springfield",
        "province": "Illinois"
    }
}

### getClient
GET http://localhost:3000/clients/{{clientId}}
Authorization: Bearer {{token}}

### getClients
GET http://localhost:3000/clients/
Authorization: Bearer {{token}}

### updateClient
PATCH http://localhost:3000/clients/{{clientId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "John Doe Updated",
    "cif": "A12345678",
    "address": {
        "street": "Updated Street",
        "number": 456,
        "postal": 54321,
        "city": "Updated City",
        "province": "Updated Province"
    }
}

### deleteClient
DELETE http://localhost:3000/clients/{{clientId}}
Authorization: Bearer {{token}}